# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8888
  servlet:
    context-path: /

spring:
  # 环境 dev|htmltest|prod|yumc-uat
  profiles:
    active: test
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**

  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /manage/**

#mybatis
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.demo.domain


